name: "PR review labeler"
description: "Adds or removes labels based on the review state of a PR"
author: "Embark Studios"
inputs:
  waitingForReview:
    description: "Comma separated list of labels to apply when the PR is waiting for review"
    required: true
  readyForMerge:
    description: "Comma separated list of labels to apply when all reviews have been approved"
    required: true
  requireDescription:
    description: "Won't add readyForMerge labels if the PR does not have a description"
    default: "true"
    required: false
  requiredChecks:
    description: "The check contexts that must pass for the `ciPassed` label(s) to be applied, if none, all are required"
    required: false
  ciPassed:
    description: "Comma separated list of labels to apply when CI has passed"
    required: true
  waitingForAuthor:
    description: "When `requireDescription` is true, and PR is otherwise ready to merge, or the PR is a draft, these labels will be used"
    required: false
  requireReview:
    description: "Won't add readyForMerge labels if the PR has not been reviewed by at least 1 person"
    default: "true"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
